export const USER_REGISTERATION="USER_REGISTERATION";
export const SET_USER_DETAILS="SET_USER_DETAILS";
export const SET_USER_CONTRACTS="SET_USER_CONTRACTS";
export const SET_USER_CONTRACTS_CONTRIBUTIONS="SET_USER_CONTRACTS_CONTRIBUTIONS";
export const SET_LOGIN_USER="SET_LOGIN_USER";
export const SET_IMAGE="SET_IMAGE";
export const LOGOUT="LOGOUT";


export const SET_CONTRACT_DATA="SET_CONTRACT_DATA";